name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Correct distribution for JDK 21
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew  # Ensure gradlew has execute permission

      - name: Set environments
        run: |
          {
            echo "version=v$(grep -oP 'versionName\s*=\s*\"\K[^\"]+' app/build.gradle.kts)"
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
            echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
          } >> $GITHUB_ENV

      - name: Build
        run: |
          if [ "${{ secrets.STORE_FILE }}" != "" ]; then
            echo "${{ secrets.STORE_FILE }}" | base64 -d > app/release.jks
            export STORE_PASSWORD="${{ secrets.STORE_PASSWORD }}"
            export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
            export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
          fi
          ./gradlew assemble --no-daemon --stacktrace --info --warning-mode=all

      - name: Debug build output
        run: ls -R app/build/outputs/apk/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repo }}(${{ env.version }}@${{ env.commit }})
          path: app/build/outputs/apk/**/app-*.apk
